/* Arquivo gerado automaticamente por UAI Design System */
import { Config } from 'tailwindcss'
            import pluginAspectRatio from '@tailwindcss/aspect-ratio'
            import pluginForms from '@tailwindcss/forms'

            export default {
              content: [],
              theme: {
  "container": {
    "center": true,
    "padding": {
      "DEFAULT": "1rem",
      "sm": "1rem",
      "md": "2rem",
      "lg": "2rem",
      "xl": "2rem",
      "2xl": "2rem"
    }
  },
  "opacity": {
    "0": "0",
    "1": "0.1",
    "2": "0.2",
    "3": "0.3",
    "4": "0.4",
    "5": "0.5",
    "6": "0.6",
    "7": "0.7",
    "8": "0.8",
    "9": "0.9",
    "10": "0.10",
    "11": "0.11",
    "12": "0.12",
    "13": "0.13",
    "14": "0.14",
    "15": "0.15",
    "16": "0.16",
    "17": "0.17",
    "18": "0.18",
    "19": "0.19",
    "20": "0.20",
    "21": "0.21",
    "22": "0.22",
    "23": "0.23",
    "24": "0.24",
    "25": "0.25",
    "26": "0.26",
    "27": "0.27",
    "28": "0.28",
    "29": "0.29",
    "30": "0.30",
    "31": "0.31",
    "32": "0.32",
    "33": "0.33",
    "34": "0.34",
    "35": "0.35",
    "36": "0.36",
    "37": "0.37",
    "38": "0.38",
    "39": "0.39",
    "40": "0.40",
    "41": "0.41",
    "42": "0.42",
    "43": "0.43",
    "44": "0.44",
    "45": "0.45",
    "46": "0.46",
    "47": "0.47",
    "48": "0.48",
    "49": "0.49",
    "50": "0.50",
    "51": "0.51",
    "52": "0.52",
    "53": "0.53",
    "54": "0.54",
    "55": "0.55",
    "56": "0.56",
    "57": "0.57",
    "58": "0.58",
    "59": "0.59",
    "60": "0.60",
    "61": "0.61",
    "62": "0.62",
    "63": "0.63",
    "64": "0.64",
    "65": "0.65",
    "66": "0.66",
    "67": "0.67",
    "68": "0.68",
    "69": "0.69",
    "70": "0.70",
    "71": "0.71",
    "72": "0.72",
    "73": "0.73",
    "74": "0.74",
    "75": "0.75",
    "76": "0.76",
    "77": "0.77",
    "78": "0.78",
    "79": "0.79",
    "80": "0.80",
    "81": "0.81",
    "82": "0.82",
    "83": "0.83",
    "84": "0.84",
    "85": "0.85",
    "86": "0.86",
    "87": "0.87",
    "88": "0.88",
    "89": "0.89",
    "90": "0.90",
    "91": "0.91",
    "92": "0.92",
    "93": "0.93",
    "94": "0.94",
    "95": "0.95",
    "96": "0.96",
    "97": "0.97",
    "98": "0.98",
    "99": "0.99",
    "100": "1"
  },
  "extend": {
    "borderRadius": {
      "avatar": "var(--uai-border-radius-avatar)",
      "badge": "var(--uai-border-radius-badge)",
      "blockcontent": "var(--uai-border-radius-blockcontent)",
      "button": "var(--uai-border-radius-button)",
      "button-icon": "var(--uai-border-radius-button-icon)",
      "card": "var(--uai-border-radius-card)",
      "check": "var(--uai-border-radius-check)",
      "drawer": "var(--uai-border-radius-drawer)",
      "dropdown": "var(--uai-border-radius-dropdown)",
      "editor": "var(--uai-border-radius-editor)",
      "file-attachment": "var(--uai-border-radius-file-attachment)",
      "input": "var(--uai-border-radius-input)",
      "large": "var(--uai-border-radius-large)",
      "medium": "var(--uai-border-radius-medium)",
      "modal": "var(--uai-border-radius-modal)",
      "none": "var(--uai-border-radius-none)",
      "pill": "var(--uai-border-radius-pill)",
      "small": "var(--uai-border-radius-small)",
      "tab": "var(--uai-border-radius-tab)",
      "text-area": "var(--uai-border-radius-text-area)",
      "toasty": "var(--uai-border-radius-toasty)"
    },
    "borderWidth": {
      "hairline": "var(--uai-border-width-hairline)",
      "none": "var(--uai-border-width-none)",
      "thick": "var(--uai-border-width-thick)",
      "thin": "var(--uai-border-width-thin)"
    },
    "outlineWidth": {
      "hairline": "var(--uai-outline-width-hairline)",
      "none": "var(--uai-outline-width-none)",
      "thick": "var(--uai-outline-width-thick)",
      "thin": "var(--uai-outline-width-thin)"
    },
    "colors": {
      "alert-100": "rgb(var(--uai-colors-alert-100) / <alpha-value>)",
      "alert-200": "rgb(var(--uai-colors-alert-200) / <alpha-value>)",
      "alert-300": "rgb(var(--uai-colors-alert-300) / <alpha-value>)",
      "alert-400": "rgb(var(--uai-colors-alert-400) / <alpha-value>)",
      "alert-500": "rgb(var(--uai-colors-alert-500) / <alpha-value>)",
      "alert-600": "rgb(var(--uai-colors-alert-600) / <alpha-value>)",
      "alert-700": "rgb(var(--uai-colors-alert-700) / <alpha-value>)",
      "alert-800": "rgb(var(--uai-colors-alert-800) / <alpha-value>)",
      "alert-900": "rgb(var(--uai-colors-alert-900) / <alpha-value>)",
      "background-contrast-brand": "rgb(var(--uai-colors-background-contrast-brand) / <alpha-value>)",
      "background-contrast-critical": "rgb(var(--uai-colors-background-contrast-critical) / <alpha-value>)",
      "background-contrast-disable": "rgb(var(--uai-colors-background-contrast-disable) / <alpha-value>)",
      "background-contrast-focus": "rgb(var(--uai-colors-background-contrast-focus) / <alpha-value>)",
      "background-contrast-idle": "rgb(var(--uai-colors-background-contrast-idle) / <alpha-value>)",
      "background-contrast-soft": "rgb(var(--uai-colors-background-contrast-soft) / <alpha-value>)",
      "background-contrast-soft-critical": "rgb(var(--uai-colors-background-contrast-soft-critical) / <alpha-value>)",
      "background-contrast-soft-success": "rgb(var(--uai-colors-background-contrast-soft-success) / <alpha-value>)",
      "background-contrast-soft-warning": "rgb(var(--uai-colors-background-contrast-soft-warning) / <alpha-value>)",
      "background-contrast-success": "rgb(var(--uai-colors-background-contrast-success) / <alpha-value>)",
      "background-contrast-warning": "rgb(var(--uai-colors-background-contrast-warning) / <alpha-value>)",
      "background-main-brand": "rgb(var(--uai-colors-background-main-brand) / <alpha-value>)",
      "background-main-brand-hover": "rgb(var(--uai-colors-background-main-brand-hover) / <alpha-value>)",
      "background-main-critical": "rgb(var(--uai-colors-background-main-critical) / <alpha-value>)",
      "background-main-dark": "rgb(var(--uai-colors-background-main-dark) / <alpha-value>)",
      "background-main-disable": "rgb(var(--uai-colors-background-main-disable) / <alpha-value>)",
      "background-main-focus": "rgb(var(--uai-colors-background-main-focus) / <alpha-value>)",
      "background-main-idle": "rgb(var(--uai-colors-background-main-idle) / <alpha-value>)",
      "background-main-secondary": "rgb(var(--uai-colors-background-main-secondary) / <alpha-value>)",
      "background-main-soft": "rgb(var(--uai-colors-background-main-soft) / <alpha-value>)",
      "background-main-success": "rgb(var(--uai-colors-background-main-success) / <alpha-value>)",
      "background-main-warning": "rgb(var(--uai-colors-background-main-warning) / <alpha-value>)",
      "black": "rgb(var(--uai-colors-black) / <alpha-value>)",
      "border-contrast-disable": "rgb(var(--uai-colors-border-contrast-disable) / <alpha-value>)",
      "border-contrast-focus": "rgb(var(--uai-colors-border-contrast-focus) / <alpha-value>)",
      "border-contrast-hover": "rgb(var(--uai-colors-border-contrast-hover) / <alpha-value>)",
      "border-contrast-idle": "rgb(var(--uai-colors-border-contrast-idle) / <alpha-value>)",
      "border-main-brand": "rgb(var(--uai-colors-border-main-brand) / <alpha-value>)",
      "border-main-brand-hover": "rgb(var(--uai-colors-border-main-brand-hover) / <alpha-value>)",
      "border-main-critical": "rgb(var(--uai-colors-border-main-critical) / <alpha-value>)",
      "border-main-disable": "rgb(var(--uai-colors-border-main-disable) / <alpha-value>)",
      "border-main-focus": "rgb(var(--uai-colors-border-main-focus) / <alpha-value>)",
      "border-main-hover": "rgb(var(--uai-colors-border-main-hover) / <alpha-value>)",
      "border-main-idle": "rgb(var(--uai-colors-border-main-idle) / <alpha-value>)",
      "border-main-secondary": "rgb(var(--uai-colors-border-main-secondary) / <alpha-value>)",
      "border-main-success": "rgb(var(--uai-colors-border-main-success) / <alpha-value>)",
      "border-main-warning": "rgb(var(--uai-colors-border-main-warning) / <alpha-value>)",
      "content-contrast-critical": "rgb(var(--uai-colors-content-contrast-critical) / <alpha-value>)",
      "content-contrast-disable": "rgb(var(--uai-colors-content-contrast-disable) / <alpha-value>)",
      "content-contrast-focus": "rgb(var(--uai-colors-content-contrast-focus) / <alpha-value>)",
      "content-contrast-idle": "rgb(var(--uai-colors-content-contrast-idle) / <alpha-value>)",
      "content-contrast-success": "rgb(var(--uai-colors-content-contrast-success) / <alpha-value>)",
      "content-contrast-warning": "rgb(var(--uai-colors-content-contrast-warning) / <alpha-value>)",
      "content-main-brand": "rgb(var(--uai-colors-content-main-brand) / <alpha-value>)",
      "content-main-brand-hover": "rgb(var(--uai-colors-content-main-brand-hover) / <alpha-value>)",
      "content-main-critical": "rgb(var(--uai-colors-content-main-critical) / <alpha-value>)",
      "content-main-disable": "rgb(var(--uai-colors-content-main-disable) / <alpha-value>)",
      "content-main-focus": "rgb(var(--uai-colors-content-main-focus) / <alpha-value>)",
      "content-main-paragraphy": "rgb(var(--uai-colors-content-main-paragraphy) / <alpha-value>)",
      "content-main-placeholder": "rgb(var(--uai-colors-content-main-placeholder) / <alpha-value>)",
      "content-main-secondary": "rgb(var(--uai-colors-content-main-secondary) / <alpha-value>)",
      "content-main-success": "rgb(var(--uai-colors-content-main-success) / <alpha-value>)",
      "content-main-tittle": "rgb(var(--uai-colors-content-main-tittle) / <alpha-value>)",
      "content-main-warning": "rgb(var(--uai-colors-content-main-warning) / <alpha-value>)",
      "focus-100": "rgb(var(--uai-colors-focus-100) / <alpha-value>)",
      "focus-200": "rgb(var(--uai-colors-focus-200) / <alpha-value>)",
      "focus-300": "rgb(var(--uai-colors-focus-300) / <alpha-value>)",
      "focus-400": "rgb(var(--uai-colors-focus-400) / <alpha-value>)",
      "focus-500": "rgb(var(--uai-colors-focus-500) / <alpha-value>)",
      "focus-600": "rgb(var(--uai-colors-focus-600) / <alpha-value>)",
      "focus-700": "rgb(var(--uai-colors-focus-700) / <alpha-value>)",
      "focus-800": "rgb(var(--uai-colors-focus-800) / <alpha-value>)",
      "focus-900": "rgb(var(--uai-colors-focus-900) / <alpha-value>)",
      "mono-100": "rgb(var(--uai-colors-mono-100) / <alpha-value>)",
      "mono-200": "rgb(var(--uai-colors-mono-200) / <alpha-value>)",
      "mono-300": "rgb(var(--uai-colors-mono-300) / <alpha-value>)",
      "mono-400": "rgb(var(--uai-colors-mono-400) / <alpha-value>)",
      "mono-500": "rgb(var(--uai-colors-mono-500) / <alpha-value>)",
      "mono-600": "rgb(var(--uai-colors-mono-600) / <alpha-value>)",
      "mono-700": "rgb(var(--uai-colors-mono-700) / <alpha-value>)",
      "mono-800": "rgb(var(--uai-colors-mono-800) / <alpha-value>)",
      "mono-900": "rgb(var(--uai-colors-mono-900) / <alpha-value>)",
      "negative-100": "rgb(var(--uai-colors-negative-100) / <alpha-value>)",
      "negative-200": "rgb(var(--uai-colors-negative-200) / <alpha-value>)",
      "negative-300": "rgb(var(--uai-colors-negative-300) / <alpha-value>)",
      "negative-400": "rgb(var(--uai-colors-negative-400) / <alpha-value>)",
      "negative-500": "rgb(var(--uai-colors-negative-500) / <alpha-value>)",
      "negative-600": "rgb(var(--uai-colors-negative-600) / <alpha-value>)",
      "negative-700": "rgb(var(--uai-colors-negative-700) / <alpha-value>)",
      "negative-800": "rgb(var(--uai-colors-negative-800) / <alpha-value>)",
      "negative-900": "rgb(var(--uai-colors-negative-900) / <alpha-value>)",
      "primary-100": "rgb(var(--uai-colors-primary-100) / <alpha-value>)",
      "primary-200": "rgb(var(--uai-colors-primary-200) / <alpha-value>)",
      "primary-300": "rgb(var(--uai-colors-primary-300) / <alpha-value>)",
      "primary-400": "rgb(var(--uai-colors-primary-400) / <alpha-value>)",
      "primary-500": "rgb(var(--uai-colors-primary-500) / <alpha-value>)",
      "primary-600": "rgb(var(--uai-colors-primary-600) / <alpha-value>)",
      "primary-700": "rgb(var(--uai-colors-primary-700) / <alpha-value>)",
      "primary-800": "rgb(var(--uai-colors-primary-800) / <alpha-value>)",
      "primary-900": "rgb(var(--uai-colors-primary-900) / <alpha-value>)",
      "secondary-100": "rgb(var(--uai-colors-secondary-100) / <alpha-value>)",
      "secondary-200": "rgb(var(--uai-colors-secondary-200) / <alpha-value>)",
      "secondary-300": "rgb(var(--uai-colors-secondary-300) / <alpha-value>)",
      "secondary-400": "rgb(var(--uai-colors-secondary-400) / <alpha-value>)",
      "secondary-500": "rgb(var(--uai-colors-secondary-500) / <alpha-value>)",
      "secondary-600": "rgb(var(--uai-colors-secondary-600) / <alpha-value>)",
      "secondary-700": "rgb(var(--uai-colors-secondary-700) / <alpha-value>)",
      "secondary-800": "rgb(var(--uai-colors-secondary-800) / <alpha-value>)",
      "secondary-900": "rgb(var(--uai-colors-secondary-900) / <alpha-value>)",
      "success-100": "rgb(var(--uai-colors-success-100) / <alpha-value>)",
      "success-200": "rgb(var(--uai-colors-success-200) / <alpha-value>)",
      "success-300": "rgb(var(--uai-colors-success-300) / <alpha-value>)",
      "success-400": "rgb(var(--uai-colors-success-400) / <alpha-value>)",
      "success-500": "rgb(var(--uai-colors-success-500) / <alpha-value>)",
      "success-600": "rgb(var(--uai-colors-success-600) / <alpha-value>)",
      "success-700": "rgb(var(--uai-colors-success-700) / <alpha-value>)",
      "success-800": "rgb(var(--uai-colors-success-800) / <alpha-value>)",
      "success-900": "rgb(var(--uai-colors-success-900) / <alpha-value>)",
      "surface-contrast-idle": "rgb(var(--uai-colors-surface-contrast-idle) / <alpha-value>)",
      "surface-contrast-soft": "rgb(var(--uai-colors-surface-contrast-soft) / <alpha-value>)",
      "surface-main-brand": "rgb(var(--uai-colors-surface-main-brand) / <alpha-value>)",
      "surface-main-critical": "rgb(var(--uai-colors-surface-main-critical) / <alpha-value>)",
      "surface-main-disable": "rgb(var(--uai-colors-surface-main-disable) / <alpha-value>)",
      "surface-main-focus": "rgb(var(--uai-colors-surface-main-focus) / <alpha-value>)",
      "surface-main-idle": "rgb(var(--uai-colors-surface-main-idle) / <alpha-value>)",
      "surface-main-secondary": "rgb(var(--uai-colors-surface-main-secondary) / <alpha-value>)",
      "surface-main-soft": "rgb(var(--uai-colors-surface-main-soft) / <alpha-value>)",
      "surface-main-success": "rgb(var(--uai-colors-surface-main-success) / <alpha-value>)",
      "surface-main-warning": "rgb(var(--uai-colors-surface-main-warning) / <alpha-value>)",
      "transparent": "rgb(var(--uai-colors-transparent) / 0)",
      "white": "rgb(var(--uai-colors-white) / <alpha-value>)",
      "facebook-brand": "rgb(var(--uai-colors-facebook-brand) / <alpha-value>)",
      "facebook-hover": "rgb(var(--uai-colors-facebook-hover) / <alpha-value>)",
      "facebook-hover-light": "rgb(var(--uai-colors-facebook-hover-light) / <alpha-value>)",
      "facebook-light": "rgb(var(--uai-colors-facebook-light) / <alpha-value>)",
      "whatsapp-brand": "rgb(var(--uai-colors-whatsapp-brand) / <alpha-value>)",
      "whatsapp-hover": "rgb(var(--uai-colors-whatsapp-hover) / <alpha-value>)",
      "whatsapp-light": "rgb(var(--uai-colors-whatsapp-light) / <alpha-value>)",
      "twitter-brand": "rgb(var(--uai-colors-twitter-brand) / <alpha-value>)",
      "twitter-hover": "rgb(var(--uai-colors-twitter-hover) / <alpha-value>)",
      "twitter-light": "rgb(var(--uai-colors-twitter-light) / <alpha-value>)",
      "google-brand": "rgb(var(--uai-colors-google-brand) / <alpha-value>)",
      "google-hover": "rgb(var(--uai-colors-google-hover) / <alpha-value>)",
      "google-text": "rgb(var(--uai-colors-google-text) / <alpha-value>)",
      "youtube-brand": "rgb(var(--uai-colors-youtube-brand) / <alpha-value>)",
      "youtube-hover": "rgb(var(--uai-colors-youtube-hover) / <alpha-value>)",
      "youtube-text": "rgb(var(--uai-colors-youtube-text) / <alpha-value>)"
    },
    "fontFamily": {
      "body-bold": "var(--uai-font-family-body-bold)",
      "body-regular": "var(--uai-font-family-body-regular)",
      "heading-bold": "var(--uai-font-family-heading-bold)",
      "heading-regular": "var(--uai-font-family-heading-regular)"
    },
    "fontSize": {
      "display": "var(--uai-font-size-display)",
      "giant": "var(--uai-font-size-giant)",
      "huge": "var(--uai-font-size-huge)",
      "large": "var(--uai-font-size-large)",
      "medium": "var(--uai-font-size-medium)",
      "nano": "var(--uai-font-size-nano)",
      "small": "var(--uai-font-size-small)",
      "xdisplay": "var(--uai-font-size-xdisplay)",
      "xgiant": "var(--uai-font-size-xgiant)",
      "xhuge": "var(--uai-font-size-xhuge)",
      "xlarge": "var(--uai-font-size-xlarge)",
      "xnano": "var(--uai-font-size-xnano)",
      "xsmall": "var(--uai-font-size-xsmall)",
      "xxgiant": "var(--uai-font-size-xxgiant)",
      "xxhuge": "var(--uai-font-size-xxhuge)",
      "xxlarge": "var(--uai-font-size-xxlarge)",
      "xxnano": "var(--uai-font-size-xxnano)",
      "xxsmall": "var(--uai-font-size-xxsmall)",
      "xxxnano": "var(--uai-font-size-xxxnano)"
    },
    "fontWeight": {
      "body-bold": "var(--uai-font-weight-body-bold)",
      "body-regular": "var(--uai-font-weight-body-regular)",
      "heading-bold": "var(--uai-font-weight-heading-bold)",
      "heading-regular": "var(--uai-font-weight-heading-regular)"
    },
    "letterSpacing": {
      "loose": "var(--uai-letter-spacing-loose)",
      "normal": "var(--uai-letter-spacing-normal)",
      "tight": "var(--uai-letter-spacing-tight)",
      "xloose": "var(--uai-letter-spacing-xloose)",
      "xtight": "var(--uai-letter-spacing-xtight)"
    },
    "lineHeight": {
      "loose": "var(--uai-line-height-loose)",
      "normal": "var(--uai-line-height-normal)",
      "tight": "var(--uai-line-height-tight)",
      "xloose": "var(--uai-line-height-xloose)",
      "xtight": "var(--uai-line-height-xtight)"
    },
    "boxShadow": {
      "focus": "var(--uai-box-shadow-focus)",
      "large": "var(--uai-box-shadow-large)",
      "medium": "var(--uai-box-shadow-medium)",
      "small": "var(--uai-box-shadow-small)",
      "xlarge": "var(--uai-box-shadow-xlarge)"
    },
    "dropShadow": {
      "focus": "var(--uai-drop-shadow-focus)",
      "large": "var(--uai-drop-shadow-large)",
      "medium": "var(--uai-drop-shadow-medium)",
      "small": "var(--uai-drop-shadow-small)",
      "xlarge": "var(--uai-drop-shadow-xlarge)"
    },
    "spacing": {
      "button": "var(--uai-spacing-button)",
      "divider": "var(--uai-spacing-divider)",
      "giant": "var(--uai-spacing-giant)",
      "huge": "var(--uai-spacing-huge)",
      "input": "var(--uai-spacing-input)",
      "large": "var(--uai-spacing-large)",
      "medium": "var(--uai-spacing-medium)",
      "nano": "var(--uai-spacing-nano)",
      "radio-checkbox": "var(--uai-spacing-radio-checkbox)",
      "small": "var(--uai-spacing-small)",
      "xgiant": "var(--uai-spacing-xgiant)",
      "xhuge": "var(--uai-spacing-xhuge)",
      "xlarge": "var(--uai-spacing-xlarge)",
      "xnano": "var(--uai-spacing-xnano)",
      "xsmall": "var(--uai-spacing-xsmall)",
      "xxgiant": "var(--uai-spacing-xxgiant)",
      "xxhuge": "var(--uai-spacing-xxhuge)",
      "xxlarge": "var(--uai-spacing-xxlarge)",
      "xxnano": "var(--uai-spacing-xxnano)",
      "xxsmall": "var(--uai-spacing-xxsmall)"
    }
  }
},
              plugins: [pluginAspectRatio, pluginForms],
            } satisfies Config
          